### ISSUE TITLE
New Fit Error

### ISSUE THREAD

**Issue by TreyHeaney** [EVE-Workbench/abyss-tracker.Issues#3]
**Describe the bug**
Upon attempting to submit a new fit I persistently receive the following error. 

` Something went wrong

Could not save fit: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`abyss`.`fit_logs`, CONSTRAINT `fit_logs_fit_it_foreign` FOREIGN KEY (`fit_it`) REFERENCES `fits` (`ID`)) (SQL: insert into `fit_logs` (`fit_it`, `fit_root_id`, `event`) values (0, 0, Could not submit fit for stats calculation.))
`
**Screenshots**
![K2J2pCU](https://github.com/EVE-Workbench/abyss-tracker.Issues/assets/66931942/75a96c97-f113-453f-af25-ad036cbe942f)

**Additional context**
The error persists when copying and pasting from different sources. A little nitty here, but users should not be forwarded error logs but rather some type of hash of error logs that can be used to pull unhashed stored logs.

**Comment by Lionear** [comment]
@TreyHeaney we've found the issue and are working on a solution right now.
While you are technically right that these errors should not be pushed to the user we are not going to resolve that in this version of the Abyss Tracker.

There is a  **GOOD** reason why we are rebuilding the entire website on our EVE Workbench stack ;)

**Comment by Lionear** [comment]
Issue has been resolved!
