### ISSUE TITLE
Scale up Abyss Site

### ISSUE THREAD

**Issue by jorgejch** [EVE-Workbench/abyss-tracker.Issues#4]
**Is your feature request related to a problem? Please describe.**
The Abyss site is slow and needs to scale up.

**Describe the solution you'd like**
Give it more juice.

**Comment by Lionear** [comment]
@jorgejch we are aware of the issues with the production site of the Abyss Tracker. 

But, we are not going to scale the available resources for this site. Reason is that we are rebuilding the website to a new stack. 

This site is already ready for use but doesn't contain all the data. You can visit the new website through [https://preview.abysstracker.com](https://preview.abysstracker.com). The website is production ready and needs active users.
