### ISSUE TITLE
Fit overview is missing a "k" on the EHP.

### ISSUE THREAD

**Issue by kennethjor** [EVE-Workbench/abyss-tracker.Issues#5]
**Describe the bug**
The fitting overview on the front page is missing a "k" in the EHP column.

**Screenshots**
![image](https://github.com/EVE-Workbench/abyss-tracker.Issues/assets/289163/5dd7baf4-686d-4f65-b239-3ba8edb5aeda)

**Comment by Lionear** [comment]
@kennethjor will be fixed in the next release
![image](https://github.com/EVE-Workbench/abyss-tracker.Issues/assets/6653342/02c85431-3bf7-41c3-86d1-c7d42d924bcd)

thanks for reporting :)

**Comment by Lionear** [comment]
@kennethjor this issus has been resolved
